const roles = {
  // --- base ---
  citizen: { faName: "شهروند ساده", teamFa: "شهر", hintFa: "بدون قابلیت", descFa: "قابلیت شب ندارید. روزها با صحبت، استدلال و رأی درست به پیدا شدن مافیا کمک کنید." },
  mafia: { faName: "مافیا ساده", teamFa: "مافیا", hintFa: "بدون قابلیت", descFa: "قابلیت مستقل ندارید. شب‌ها با مافیا مشورت می‌کنید و روزها تلاش می‌کنید شهر را گمراه کنید." },

  // --- classic / general ---
  mafiaBoss: { faName: "رئیس مافیا", teamFa: "مافیا", hintFa: "رهبر + شلیک", descFa: "رهبر تیم مافیاست؛ تصمیم نهاییِ شلیک شب با اوست و معمولاً استعلام او برای کارآگاه «منفی» است." },
  godfather: { faName: "پدرخوانده", teamFa: "مافیا", hintFa: "رهبر + شلیک", descFa: "در بسیاری از سناریوها همان رهبر مافیاست و شلیک شب را تعیین می‌کند. در نسخهٔ رایج، استعلام او برای کارآگاه «منفی» است." },
  swindler: { faName: "شیاد", teamFa: "مافیا", hintFa: "برهم‌زنِ استعلام", descFa: "نقش مافیاییِ برهم‌زن استعلام (در بعضی سناریوها). هر شب روی یک نفر اثر می‌گذارد؛ توضیح دقیق به سناریو بستگی دارد." },
  nato: { faName: "ناتو", teamFa: "مافیا", hintFa: "حدسِ نقش", descFa: "یک شب (طبق سناریو) نقش دقیقِ یک بازیکن را حدس می‌زند؛ در صورت حدس درست، آن بازیکن از بازی خارج می‌شود." },
  negotiator: { faName: "مذاکره‌کننده", teamFa: "مافیا", hintFa: "مذاکره/تبدیل", descFa: "می‌تواند (طبق سناریو) در شب مذاکره تلاش کند یک شهروند را به تیم مافیا اضافه کند؛ در شب مذاکره معمولاً شلیک انجام نمی‌شود." },
  natasha: { faName: "ناتاشا", teamFa: "مافیا", hintFa: "سایلنتِ شب", descFa: "نقش مافیاییِ سایلنت‌کننده است: شب‌ها یک نفر را انتخاب می‌کند تا روز بعد نتواند صحبت کند (معمولاً تکراری پشت‌سرهم نیست)." },
  doctorLecter: { faName: "دکتر لکتر", teamFa: "مافیا", hintFa: "سیوِ مافیا", descFa: "پزشکِ تیم مافیاست. معمولاً هر شب می‌تواند یک نفر را از شلیک نجات دهد و فقط یک‌بار می‌تواند خودش را نجات دهد.", canBeDisabled: true },
  jokerMafia: { faName: "جوکر مافیا", teamFa: "مافیا", hintFa: "برعکس‌کردن استعلام", descFa: "در نسخهٔ رایجِ «شب‌های مافیا»، فقط ۲ بار در کل بازی می‌تواند یک نفر را انتخاب کند تا استعلام او همان شب برای کارآگاه برعکس شود (معمولاً انتخاب تکراری پشت‌سرهم ممنوع است)." },
  matador: { faName: "ماتادور", teamFa: "مافیا", hintFa: "گرفتنِ قابلیت", descFa: "شب‌ها می‌تواند یک نفر را انتخاب کند تا تواناییِ شبِ او همان شب غیرفعال شود (طبق سناریو)." },
  saulGoodman: { faName: "ساول گودمن", teamFa: "مافیا", hintFa: "خرید/سوداگری", descFa: "طبق سناریو (مثلاً پدرخوانده) یک‌بار می‌تواند یک شهروند ساده را به مافیا تبدیل کند." },

  detective: { faName: "کارآگاه", teamFa: "شهر", hintFa: "استعلامِ شب", descFa: "هر شب می‌تواند یک نفر را استعلام کند تا مافیایی/شهروندی بودن او را بفهمد (طبق سناریو).", canBeDisabled: true },
  investigator: { faName: "بازپرس", teamFa: "شهر", hintFa: "بازپرسی", descFa: "در برخی سناریوها یک‌بار در طول بازی می‌تواند بازپرسی انجام دهد (جزئیات بسته به سناریو است)." },
  doctor: { faName: "پزشک", teamFa: "شهر", hintFa: "سیوِ شب", descFa: "هر شب می‌تواند جان یک نفر را از شلیک نجات دهد. در نسخهٔ رایج، وقتی بازیکنان زیاد باشند ۲ انتخاب دارد و نجاتِ خودش محدود است.", canBeDisabled: true },
  watson: { faName: "دکتر واتسون", teamFa: "شهر", hintFa: "نجات", descFa: "در سناریو پدرخوانده نقش پزشک شهر است (طبق قوانین میز).", canBeDisabled: true },
  researcher: { faName: "محقق", teamFa: "شهر", hintFa: "گره/پیوند", descFa: "در نسخهٔ رایجِ «شهروند و مافیا»، (به‌جز شب معارفه) می‌تواند خودش را به یک نفر گره بزند؛ اگر محقق با شات شب یا رأی از بازی خارج شود، آن نفر هم با او خارج می‌شود (با استثناهایی مثل رئیس مافیا)." },
  invulnerable: { faName: "رویین‌تن", teamFa: "شهر", hintFa: "زرهِ شب", descFa: "در نسخهٔ رایج، شب‌ها با شلیک مافیا کشته نمی‌شود و فقط با رأی/شرایط خاص از بازی خارج می‌شود." },
  armored: { faName: "زره‌پوش", teamFa: "شهر", hintFa: "زره + بازگشت", descFa: "در نسخهٔ رایج، شب با تیر مافیا کشته نمی‌شود. اگر روز با رأی از بازی خارج شود، نقشش افشا می‌شود و به بازی برمی‌گردد (و از آن به بعد قابل مذاکره نیست)." },
  sniper: { faName: "تک‌تیرانداز", teamFa: "شهر", hintFa: "شلیکِ محدود", descFa: "معمولاً فقط یک‌بار اجازه شلیک دارد. اگر به اشتباه به شهروند شلیک کند، خودش از بازی خارج می‌شود (حتی اگر پزشک او را نجات دهد)." },
  professional: { faName: "حرفه‌ای", teamFa: "شهر", hintFa: "شلیک", descFa: "شب‌ها می‌تواند به کسی که مافیایی می‌داند شلیک کند؛ اگر اشتباه به شهروند شلیک کند، خودش از بازی خارج می‌شود.", canBeDisabled: true },
  reporter: { faName: "خبرنگار", teamFa: "شهر", hintFa: "استعلامِ مذاکره", descFa: "در سناریو مذاکره‌کننده، از شبی که مذاکره انجام می‌شود بیدار می‌شود و استعلامِ فردِ مذاکره‌شده را می‌گیرد؛ اگر درست تشخیص دهد، گرداننده تأیید می‌کند." },
  representative: { faName: "نماینده", teamFa: "شهر", hintFa: "قدرتِ روز", descFa: "در این نسخه فقط به‌عنوان نقش سناریو «نماینده» تعریف شده است (قوانین دقیقش بسته به نسخهٔ سناریو متفاوت است)." },
  hardJohn: { faName: "جان‌سخت", teamFa: "شهر", hintFa: "جان اضافه + استعلام", descFa: "با شلیک اولِ مافیا از بازی خارج نمی‌شود (معمولاً خودش متوجه نمی‌شود). همچنین معمولاً دوبار می‌تواند وضعیت/سایدِ نفراتِ خارج‌شده را از گرداننده استعلام بگیرد." },
  psychologist: { faName: "روانپزشک", teamFa: "شهر", hintFa: "قطع مکالمه", descFa: "معمولاً دو بار در طول بازی می‌تواند توانایی صحبت/مکالمهٔ یک بازیکن را بگیرد." },
  mayor: { faName: "شهردار", teamFa: "شهر", hintFa: "وتو/خروج", descFa: "معمولاً فقط یک‌بار (وقتی حداقل ۲ نفر در دفاعیه باشند و خودش در دفاعیه نباشد) می‌تواند رأی‌گیریِ دور دوم را لغو کند یا حکمِ خروج مستقیم یکی از افرادِ دفاعیه را بدهد." },
  seller: { faName: "فروشنده", teamFa: "شهر", hintFa: "گرفتن قابلیت", descFa: "یک‌بار در طول بازی می‌تواند تواناییِ یک نفر را برای کل بازی از او بگیرد؛ معمولاً فردای همان روز، انتخابِ فروشنده توسط راوی اعلام می‌شود." },
  priest: { faName: "کشیش", teamFa: "شهر", hintFa: "حمایتِ گفت‌وگو", descFa: "طبق نسخهٔ رایج، شب‌ها چند نفر را انتخاب می‌کند تا روز بعد حق صحبت اضافه داشته باشند؛ همچنین می‌تواند برخی اثرهای سکوت را خنثی کند (طبق سناریو)." },
  judge: { faName: "قاضی", teamFa: "شهر", hintFa: "تغییر رأی", descFa: "یک‌بار می‌تواند نتیجهٔ رأی‌گیریِ روز را تغییر دهد/ملغی کند (طبق سناریو؛ معمولاً در شب اعمال می‌شود)." },
  commander: { faName: "فرمانده", teamFa: "شهر", hintFa: "تأیید شلیک", descFa: "بعد از شلیکِ اسنایپر بیدار می‌شود و می‌تواند شلیک را تأیید یا رد کند؛ اگر رد کند، تیر اصابت نمی‌کند (طبق سناریو)." },

  // --- Capo (کاپو/دن) ---
  danMafia: { faName: "دن مافیا", teamFa: "مافیا", hintFa: "رئیس + پادزهر", descFa: "رئیس تیم مافیاست و استعلام او برای کارآگاه «منفی» است. یک پادزهر دارد (مثلاً در صورت زهرِ عطار). همچنین قابلیت سوداگری/خریدِ برخی نقش‌های شهر را دارد (طبق سناریو کاپو)." },
  witch: { faName: "جادوگر", teamFa: "مافیا", hintFa: "کپیِ قابلیت", descFa: "هر شب یک شهروند را انتخاب می‌کند؛ اگر آن شهروند ابلیتی‌دار باشد، ابلیتیِ او روی خودِ جادوگر اجرا می‌شود (مثلاً از زره‌ساز زره می‌گیرد، از کارآگاه استعلام می‌گیرد، از عطار برای خودش زهر می‌ریزد) (طبق سناریو کاپو)." },
  executioner: { faName: "جلاد", teamFa: "مافیا", hintFa: "حدسِ نقش", descFa: "مشابه «ناتو»: اگر نقشِ یک نفر را درست حدس بزند، آن نفر تحت هر شرایطی از بازی خارج می‌شود (طبق سناریو کاپو)." },
  informant: { faName: "خبرچین", teamFa: "مافیا", hintFa: "جاسوس", descFa: "جاسوس تیم مافیاست. اگر کدخدا او را بیدار کند، مثل شهروند بیدار می‌شود (طبق سناریو کاپو)." },
  kadkhoda: { faName: "کدخدا", teamFa: "شهر", hintFa: "لینکِ شهر", descFa: "در طول بازی می‌تواند ۲ نفر را به «لینک شهروندی» وصل کند. در شبِ لینک‌کردن، اگر شهروند/خبرچین باشند با او بیدار می‌شوند (بدون گفتن نقش). اگر کدخدا اشتباه یک مافیا (جز خبرچین) را بیدار کند، مرگ کدخدا اتفاق می‌افتد (طبق سناریو کاپو)." },
  heir: { faName: "وارث", teamFa: "شهر", hintFa: "ارثِ نقش", descFa: "شب معارفه یک نفر را انتخاب می‌کند. اگر آن نفر از بازی خارج شود، وارث (فقط در برخی نقش‌ها مثل کارآگاه/زره‌ساز/عطار) تواناییِ او را به ارث می‌برد. تا قبل از گرفتنِ نقش، نامیراست (طبق سناریو کاپو)." },
  herbalist: { faName: "عطار", teamFa: "شهر", hintFa: "زهر + پادزهر", descFa: "یک پادزهر دارد و یک زهر: هر شب می‌تواند زهر بدهد؛ صبح اعلام می‌شود زهر وارد بازی شده و اگر تا پایان روز فردِ مسموم خارج نشود، با رأی‌گیریِ شب مشخص می‌شود پادزهر داده شود یا نه (طبق سناریو کاپو)." },
  armorsmith: { faName: "زره‌ساز", teamFa: "شهر", hintFa: "نجاتِ یک‌باره", descFa: "یک‌بار در کل بازی می‌تواند خودش را نجات دهد (طبق سناریو کاپو)." },
  suspect: { faName: "مظنون", teamFa: "شهر", hintFa: "استعلامِ مثبت", descFa: "شهروند است اما استعلام او برای کارآگاه «مثبت» است (طبق سناریو کاپو)." },

  // --- Zodiac ---
  alcapone: { faName: "آلکاپن", teamFa: "مافیا", hintFa: "رئیس", descFa: "رئیس مافیاست و استعلام او برای کارآگاه منفی است (طبق سناریو زودیاک)." },
  zodiac: { faName: "زودیاک", teamFa: "مستقل", hintFa: "شلیکِ شب‌های زوج", descFa: "تیم مستقل است. معمولاً در شب‌های زوج می‌تواند به شهروند یا مافیا شلیک کند و یک نفر را از بازی خارج کند. با شلیک شب کشته نمی‌شود و معمولاً فقط با رأی‌گیری یا بمب‌گذاری (و در برخی قوانین با شلیکِ تفنگ در روز) از بازی خارج می‌شود. اگر به «محافظ» شلیک کند، خودش کشته می‌شود.", canBeDisabled: true },
  magician: { faName: "شعبده‌باز", teamFa: "مافیا", hintFa: "گرفتن قابلیت", descFa: "هر شب (با هماهنگی تیم مافیا) یک نفر از شهر را انتخاب می‌کند و تواناییِ او را می‌گیرد/غیرفعال می‌کند." },
  bomber: { faName: "بمب‌گذار", teamFa: "مافیا", hintFa: "بمب‌گذاری", descFa: "یک‌بار در طول بازی می‌تواند بمب‌گذاری کند: یک «کد ۱ تا ۴» به گرداننده می‌دهد و بازیکنِ هدف فقط اگر کد را درست حدس بزند در بازی می‌ماند.", canBeDisabled: true },
  guard: { faName: "محافظ", teamFa: "شهر", hintFa: "ضد بمب/زودیاک", descFa: "در زمان بمب‌گذاری می‌تواند خودش را فدای نفرِ هدف کند. سپس کدِ خنثی‌سازی را حدس می‌زند و فقط در صورت حدسِ درست در بازی می‌ماند. همچنین اگر زودیاک به محافظ شلیک کند، زودیاک کشته می‌شود.", canSacrificeForBomb: true },
  ocean: { faName: "اوشن", teamFa: "شهر", hintFa: "بیداری شهر", descFa: "معمولاً دو بار در طول بازی می‌تواند شب چند شهروند را بیدار کند تا با چشم باز با هم مشورت کنند. اگر اشتباه یکی از اعضای مافیا یا زودیاک را بیدار کند، از بازی خارج می‌شود.", canBeDisabled: true },
  gunslinger: { faName: "تفنگدار", teamFa: "شهر", hintFa: "دادن تفنگ", descFa: "سه تفنگ دارد (۲ تیر مشقی و ۱ تیر جنگی). خودش شلیک نمی‌کند؛ شب می‌تواند تفنگ را به بازیکنان بدهد و بازیکنی که تفنگ گرفته، روز بعد می‌تواند استفاده کند.", canBeDisabled: true },

  // --- Godfather (game) ---
  leon: { faName: "لئون", teamFa: "شهر", hintFa: "حرفه‌ای شهر", descFa: "نقش کلیدی شهر در سناریو پدرخوانده (طبق قوانین میز)." },
  constantine: { faName: "کنستانتین", teamFa: "شهر", hintFa: "بازگردانی", descFa: "می‌تواند طبق قوانین میز یک نفر را به بازی برگرداند (طبق سناریو پدرخوانده)." },
  citizenKane: { faName: "همشهری کین", teamFa: "شهر", hintFa: "افشا", descFa: "در سناریو پدرخوانده معمولاً یک‌بار می‌تواند یک نفر را نشان کند؛ اگر آن نفر مافیا باشد، صبح ساید او توسط گرداننده اعلام می‌شود (طبق قوانین میز)." },
  nostradamus: { faName: "نوستراداموس", teamFa: "مستقل", hintFa: "شب معارفه", descFa: "در سناریو پدرخوانده (روایت رایج)، فقط شب معارفه بیدار می‌شود و ۳ نفر را نشان می‌دهد؛ گرداننده تعداد مافیاهای داخل این ۳ نفر را اعلام می‌کند و او براساس آن، ساید خود را انتخاب می‌کند." },
};

// English role labels (UI only). If a role isn't present here, it falls back to Persian.
const ROLE_I18N = {
  citizen: { name: "Citizen", hint: "No ability", desc: "No night ability. Help find mafia through discussion and voting." },
  mafia: { name: "Mafia", hint: "No ability", desc: "No standalone ability. Coordinate at night; mislead during the day." },
  mafiaBoss: { name: "Mafia Boss", hint: "Leader + shot", desc: "Leads the mafia; usually decides the night shot. Often shows as ‘negative’ to the Detective." },
  godfather: { name: "Godfather", hint: "Leader + shot", desc: "Often the mafia leader who decides the night shot; typically shows as ‘negative’ to the Detective." },
  swindler: { name: "Charlatan", hint: "Disrupts inquiry", desc: "Disrupts inquiries (varies by scenario). Applies an effect to a target each night." },
  nato: { name: "NATO", hint: "Guess a role", desc: "Once (by scenario), guesses a player’s exact role; if correct, that player is eliminated." },
  negotiator: { name: "Negotiator", hint: "Convert", desc: "May attempt (by scenario) to convert a citizen to mafia; usually replaces the night shot." },
  natasha: { name: "Natasha", hint: "Night silence", desc: "Chooses a player to be silent the next day (rules vary)." },
  doctorLecter: { name: "Dr. Lecter", hint: "Save (mafia)", desc: "Mafia doctor. Can save a target from the night shot; self-save is usually limited." },
  jokerMafia: { name: "Mafia Joker", hint: "Flip inquiry", desc: "Limited times per game can invert a Detective inquiry result (scenario rules apply)." },
  matador: { name: "Matador", hint: "Disable ability", desc: "Chooses a player to disable their night ability for that night (by scenario)." },
  saulGoodman: { name: "Saul Goodman", hint: "Buy/convert", desc: "Once (by scenario) can convert a basic citizen into a mafia member." },

  detective: { name: "Detective", hint: "Night inquiry", desc: "Each night can check a player’s side (scenario rules apply)." },
  investigator: { name: "Inspector", hint: "Interrogation", desc: "Once per game (in some scenarios) can interrogate (details vary)." },
  doctor: { name: "Doctor", hint: "Night save", desc: "Each night can save a player from the night shot. Self-save is usually limited." },
  watson: { name: "Dr. Watson", hint: "Save", desc: "In Godfather scenario, acts as the city Doctor (table rules apply)." },
  researcher: { name: "Researcher", hint: "Link", desc: "Can link to a player; if the Researcher is eliminated, the linked player may also be eliminated (rules vary)." },
  invulnerable: { name: "Invulnerable", hint: "Night armor", desc: "Typically cannot be killed by the mafia’s night shot; eliminated via vote/special rules." },
  armored: { name: "Armored", hint: "Armor + return", desc: "Typically survives night shots; if voted out, role reveals and returns (rules vary)." },
  sniper: { name: "Sniper", hint: "Limited shot", desc: "Usually has one shot. If shoots a citizen, the Sniper is eliminated (even if saved)." },
  professional: { name: "Professional", hint: "Shot", desc: "Can shoot at night; if shoots a citizen by mistake, is eliminated." },
  reporter: { name: "Reporter", hint: "Negotiation inquiry", desc: "In negotiator scenario, gets inquiry about negotiated player (rules vary)." },
  representative: { name: "Representative", hint: "Day power", desc: "Scenario-defined role; exact rules depend on the version." },
  hardJohn: { name: "Hard John", hint: "Extra life", desc: "Usually survives the first mafia shot. Often has limited status inquiries (rules vary)." },
  psychologist: { name: "Psychiatrist", hint: "Mute", desc: "Usually can remove a player’s ability to talk a limited number of times." },
  mayor: { name: "Mayor", hint: "Veto/out", desc: "Once may veto a vote or directly eliminate a defendant (rules vary)." },
  seller: { name: "Seller", hint: "Remove ability", desc: "Once can remove a player’s ability for the rest of the game (rules vary)." },
  priest: { name: "Priest", hint: "Support talk", desc: "Chooses players to get extra talk time; may neutralize silence effects (rules vary)." },
  judge: { name: "Judge", hint: "Change vote", desc: "Once may change/void a vote result (rules vary)." },
  commander: { name: "Commander", hint: "Confirm shot", desc: "After the Sniper shoots, can confirm or cancel the shot (scenario rules apply)." },

  danMafia: { name: "Mafia Don", hint: "Leader + antidote", desc: "Mafia leader. Often shows negative to Detective; may have an antidote and trading powers (scenario rules apply)." },
  witch: { name: "Witch", hint: "Copy ability", desc: "Chooses a citizen; if they have an ability, it is applied to the Witch (scenario rules apply)." },
  executioner: { name: "Executioner", hint: "Guess a role", desc: "Like NATO: if the exact role guess is correct, the target is eliminated (scenario rules apply)." },
  informant: { name: "Informant", hint: "Spy", desc: "Mafia spy. If awakened by Kadkhoda, can wake like a citizen (scenario rules apply)." },
  kadkhoda: { name: "Kadkhoda", hint: "City link", desc: "Can link two players to a ‘citizen link’ (rules vary by scenario)." },
  heir: { name: "Heir", hint: "Inherit role", desc: "Selects a player; may inherit certain abilities if that player is eliminated (scenario rules apply)." },
  herbalist: { name: "Herbalist", hint: "Poison + antidote", desc: "Has one poison and one antidote; poisoning and antidote resolution depends on scenario rules." },
  armorsmith: { name: "Armorsmith", hint: "One-time save", desc: "Once per game can save themselves (scenario rules apply)." },
  suspect: { name: "Suspect", hint: "Positive inquiry", desc: "Citizen, but shows as ‘mafia’ to the Detective (scenario rules apply)." },

  alcapone: { name: "Al Capone", hint: "Leader", desc: "Mafia leader; typically shows negative to Detective (Zodiac scenario rules apply)." },
  zodiac: { name: "Zodiac", hint: "Even-night shot", desc: "Independent. Often can shoot on even nights; usually cannot be killed by night shot (rules vary)." },
  magician: { name: "Magician", hint: "Disable ability", desc: "Chooses a city player and disables their ability (rules vary)." },
  bomber: { name: "Bomber", hint: "Bomb", desc: "Once can plant a bomb with a code; target survives only if guessing correctly (rules vary)." },
  guard: { name: "Guard", hint: "Anti-bomb", desc: "Can sacrifice to protect a bomb target and guess the disarm code (rules vary)." },
  ocean: { name: "Ocean", hint: "Wake citizens", desc: "Limited times can wake some citizens to consult; waking mafia/Zodiac incorrectly may eliminate Ocean (rules vary)." },
  gunslinger: { name: "Gunslinger", hint: "Give guns", desc: "Gives guns at night; recipients may use them during the day (rules vary)." },

  leon: { name: "Leon", hint: "City pro", desc: "Key city role in Godfather scenario (table rules apply)." },
  constantine: { name: "Constantine", hint: "Revive", desc: "May revive a player (table rules apply)." },
  citizenKane: { name: "Citizen Kane", hint: "Reveal", desc: "Once can mark a player; if mafia, their side may be announced (rules vary)." },
  nostradamus: { name: "Nostradamus", hint: "Intro night", desc: "Only wakes on the intro night, marks 3 players; host reveals how many mafia among them (rules vary)." },
};
