const STR = {
  fa: {
    "doc.title": "اپلیکیشن بازی مافیا",
    "app.title": "اپلیکیشن بازی مافیا",
    "top.help": "راهنما",
    "top.lang.aria": "تغییر زبان",
    "top.lang.toFa": "فارسی",
    "top.lang.toEn": "English",

    "setup.title": "تنظیمات بازی",
    "setup.backToSetup": "بازگشت به تنظیمات بازی",
    "setup.scenario": "سناریو",
    "setup.playersCount": "تعداد بازیکن‌ها",
    "setup.mafiaCount": "تعداد مافیا",
    "setup.defaults": "پیش‌فرض سناریو",
    "setup.start": "شروع بازی",
    "setup.savedGame": "یک بازی ذخیره شده است.",
    "setup.resume": "ادامه بازی",
    "setup.delete": "حذف",

    "players.title": "بازیکنان",
    "players.namesModeAria": "حالت نام‌ها",
    "players.namesDefault": "اسامی پیش‌فرض",
    "players.namesLast": "اسامی بازی قبل",
    "players.note": "اسامی بازیکنان را وارد کنید. اگر «اسامی بازی قبل» را انتخاب کنید، از ذخیره‌ی مرورگر استفاده می‌شود.",
    "players.deal": "تقسیم نقش",
    "players.back": "بازگشت به تنظیمات",

    "cards.title": "تقسیم نقش",
    "cards.hint": "بازیکن یک کارت را انتخاب می‌کند و نقش خودش را می‌بیند.",
    "cards.back": "بازگشت",
    "cards.autoAssign": "اختصاص اتومات نقش‌ها",
    "cards.next": "برو مرحله بعد!",

    "cast.title": "فهرست شخصیت‌ها",
    "cast.back": "بازگشت به تنظیمات بازی",
    "cast.new": "قرعه‌کشی جدید",

    "tools.wake": "بیداری",
    "tools.status": "استعلام",
    "tools.lastMove": "حرکت آخر",
    "tools.roleChange": "تغییر نقش",
    "tools.chance": "قرعه",
    "tools.timer": "تایم",
    "tools.flow": "جریان",

    "common.close": "بستن",
    "common.seen": "دیدم",
    "common.roleHelp": "راهنمای نقش",
    "common.on": "روشن",
    "common.off": "خاموش",
    "common.done": "تمام شد",
    "common.turn": "نوبت",
    "common.playerN": "بازیکن {n}",
    "common.cardN": "کارت {n}",
    "common.taken": "برداشته شد",

    "saveState.label": "ذخیره: {state}",
    "error.config": "خطا در تنظیمات بازی.",
    "error.quick": "خطا در تنظیمات",
    "error.duplicateName": "نام «{name}» تکراری است.",

    "teams.mafia": "مافیا",
    "teams.city": "شهر",
    "teams.independent": "مستقل",
    "teams.mafiaTeam": "تیم مافیا",
    "teams.cityTeam": "تیم شهر",

    "toggles.variableCount": "تعداد: متغیر",

    "quickStat.withInd": "مافیا: {m} • شهر: {c} • مستقل: {i}",
    "quickStat.noInd": "مافیا: {m} • شهر: {c}",

    "help.title": "راهنما",
    "help.quick": "راهنمای سریع",
    "help.body": `1) سناریو، تعداد بازیکن‌ها و تعداد مافیا را تنظیم کنید.<br />
2) نقش‌های فعال را (طبق سناریو) روشن/خاموش کنید.<br />
3) «شروع بازی» را بزنید و اسامی را وارد کنید.<br />
4) «تقسیم نقش» را بزنید؛ هر بازیکن یک کارت انتخاب می‌کند و «دیدم» را می‌زند.<br />
5) در «فهرست شخصیت‌ها»، راوی می‌تواند ابزارها (تایمر/قرعه/تغییر نقش/وضعیت) را استفاده کند.`,

    "tool.wake.title": "ترتیب بیداری",
    "tool.wake.scenario": "سناریو: {name}",
    "tool.wake.none": "برای این سناریو ترتیب بیداری ثبت نشده است.",

    "tool.status.title": "استعلام وضعیت",
    "tool.status.alive": "افراد زنده",
    "tool.status.dead": "افراد مرده",
    "tool.status.mafiaAlive": "مافیا زنده",
    "tool.status.mafiaDead": "مافیا مرده",
    "tool.status.cityAlive": "شهر زنده",
    "tool.status.cityDead": "شهر مرده",
    "tool.status.indAlive": "مستقل زنده",
    "tool.status.indDead": "مستقل مرده",
    "tool.status.hint": "برای تغییر وضعیت هر بازیکن، در صفحه «فهرست شخصیت‌ها» روی نام بازیکن بزنید و «کشته شد» را انتخاب کنید.",
    "tool.status.summary": "از بازی شما {out} نفر خارج شده‌اند. {m} مافیا، {c} شهروند و {i} مستقل.",

    "tool.flow.title": "گردانندهٔ بازی",
    "tool.flow.needDeal": "ابتدا نقش‌ها را تقسیم کنید.",
    "tool.flow.phase.day": "روز {n}",
    "tool.flow.phase.midday": "خواب نیم‌روز (روز {n})",
    "tool.flow.phase.night": "شب {n}",
    "tool.flow.step": "مرحله {i} از {n}",
    "tool.flow.next": "بعدی",
    "tool.flow.prev": "قبلی",
    "tool.flow.reset": "ریست جریان",
    "tool.flow.timeline": "تایم‌لاین",
    "tool.flow.log": "رویدادها",
    "tool.flow.addNote": "ثبت یادداشت",
    "tool.flow.notePlayer": "بازیکن",
    "tool.flow.notePlaceholder": "چه اتفاقی افتاد؟",
    "tool.flow.saveNote": "ثبت",
    "tool.flow.day.talk": "نوبت صحبت",
    "tool.flow.day.guns": "شلیک تفنگ",
    "tool.flow.day.gunExpiry": "انقضای تفنگ",
    "tool.flow.day.gunExpiry.desc": "بازیکنان زیر تفنگ واقعی استفاده‌نشده دارند و با زدن «بعدی» از بازی خارج می‌شوند.",
    "tool.flow.day.gunExpiry.none": "همه تفنگ‌های واقعی استفاده شده‌اند — هیچ‌کس از این مرحله خارج نمی‌شود.",
    "tool.flow.guns.title": "مدیریت تفنگ‌ها",
    "tool.flow.guns.hasGun": "دارنده‌های تفنگ",
    "tool.flow.guns.add": "دادن تفنگ",
    "tool.flow.guns.giveTo": "دادن به",
    "tool.flow.guns.type": "نوع تفنگ",
    "tool.flow.guns.type.real": "واقعی",
    "tool.flow.guns.type.fake": "مشقی",
    "tool.flow.guns.selfFakeOnly": "تفنگدار می‌تواند به هرکسی تفنگ بدهد؛ اما به خودش فقط تفنگِ مشقی می‌تواند بدهد.",
    "tool.flow.guns.nightQuota": "سهمیهٔ این شب: {n}/2 تفنگ • واقعی: {r}/1",
    "tool.flow.guns.limit2": "در هر شب حداکثر ۲ تفنگ می‌تواند بدهد.",
    "tool.flow.guns.limit1Real": "در هر شب حداکثر ۱ تفنگ واقعی می‌تواند بدهد.",
    "tool.flow.guns.gunslingerIs": "تفنگدار: {name}",
    "tool.flow.guns.give": "ثبت تفنگ",
    "tool.flow.guns.remove": "حذف تفنگ",
    "tool.flow.guns.shooter": "شلیک‌کننده",
    "tool.flow.guns.target": "هدف",
    "tool.flow.guns.fire": "ثبت شلیک",
    "tool.flow.guns.noEffect": "تفنگ مشقی بود (بدون اثر).",
    "tool.flow.guns.killedTarget": "تفنگ واقعی بود (هدف خارج شد).",
    "tool.flow.ocean.team": "تیم اوشن (این شب)",
    "tool.flow.ocean.add": "اضافه‌کردن به تیم اوشن",
    "tool.flow.ocean.pick": "انتخاب بازیکن",
    "tool.flow.ocean.remove": "حذف از تیم",
    "tool.flow.day.vote": "رأی‌گیری",
    "tool.flow.vote.hint": "به هر بازیکنِ زنده، تعداد رأی دریافتی را بدهید.",
    "tool.flow.vote.votes": "تعداد رأی",
    "tool.flow.vote.apply": "ثبت رأی‌ها",
    "tool.flow.vote.clear": "پاک کردن",
    "tool.flow.vote.total": "مجموع رأی‌ها: {n}",
    "tool.flow.vote.leaders": "بیشترین رأی‌ها",
    "tool.flow.defense.hint": "بر اساس رأی‌های ثبت‌شده، کسانی که حدنصاب اکثریت را دارند باید دفاع کنند.",
    "tool.flow.defense.threshold": "حدنصاب اکثریت: {n} (بیش از نصفِ {v} رأی‌دهنده)",
    "tool.flow.defense.none": "کسی به حدنصاب نرسیده است.",
    "tool.flow.defense.needVotes": "ابتدا مرحله «رأی‌گیری» را ثبت کنید.",
    "tool.flow.defense.list": "لیست دفاعیه",
    "tool.flow.elim.hint": "بعد از دفاعیه، تعداد رأیِ خروج برای مظنون‌ها را ثبت کنید. بیشترین رأی = خروج. اگر مساوی شد، قرعه بزنید.",
    "tool.flow.elim.votes": "رأی خروج",
    "tool.flow.elim.apply": "ثبت نتیجه",
    "tool.flow.elim.clear": "پاک کردن",
    "tool.flow.elim.noCandidates": "کسی در لیست دفاعیه نیست.",
    "tool.flow.elim.result": "نتیجه",
    "tool.flow.elim.out": "خروج",
    "tool.flow.elim.draw": "قرعه بین مساوی‌ها",
    "tool.flow.elim.tie": "مساوی",
    "tool.flow.elim.notChosenYet": "هنوز انتخاب نشده",
    "tool.flow.elim.single.need": "حدنصاب خروج: {n} رأی (بیش از نصفِ {v} رأی‌دهنده)",
    "tool.flow.elim.single.notEnough": "رأی کافی نیست: {c} از {n}",
    "tool.flow.day.outcome": "نتیجه روز",
    "tool.flow.outcome.none": "امروز کسی با رأی از بازی خارج نشد.",
    "tool.flow.outcome.votedOut": "با رأی خارج شد:",
    "tool.flow.outcome.lastMove": "کارت حرکت آخر (فقط وقتی با رأی خارج شود)",
    "tool.flow.endCards.title": "کارت پایان",
    "tool.flow.endCards.for": "کارت پایان برای {name}: {card}",
    "tool.flow.day.defense": "دفاعیه",
    "tool.flow.day.eliminate": "خروج/نتیجه",
    "tool.flow.day.toNight": "رفتن به شب",
    "tool.flow.midday.sleepVote": "رأیِ چشم‌بسته",
    "tool.flow.midday.resolve": "نتیجه خواب نیم‌روز",
    "tool.flow.night.wake": "ترتیب بیداری",
    "tool.flow.night.actions": "ثبت اکشن‌های شب",
    "tool.flow.night.run": "ترتیب بیداری و اکشن‌های شب",
    "tool.flow.night.resolve": "جمع‌بندی شب و رفتن به روز",
    "tool.flow.action.mafiaShot": "شلیک مافیا به",
    "tool.flow.action.doctorSave": "سیو پزشک روی",
    "tool.flow.action.detectiveQuery": "استعلام کارآگاه از",
    "tool.flow.action.professionalShot": "شلیک حرفه‌ای به",
    "tool.flow.action.bomber": "بمب‌گذاری روی",
    "tool.flow.action.bombCode": "کد/رمز",
    "tool.flow.action.magicianDisable": "غیرفعال‌کردنِ شعبده‌باز",
    "tool.flow.action.zodiacShot": "شلیک زودیاک به",
    "tool.flow.action.oceanWake": "اوشن بیدار کرد",
    "tool.flow.action.kaneMark": "همشهری کین نشان کرد",
    "tool.flow.action.constantineRevive": "کنستانتین برگرداند",
    "tool.flow.action.nostPick3": "نوستراداموس ۳ نفر را نشان داد",
    "tool.flow.action.heirPick": "وارث انتخاب کرد",
    "tool.flow.action.herbalistPoison": "عطار زهر داد به",
    "tool.flow.action.herbalistAntidote": "عطار پادزهر داد به",
    "tool.flow.action.armorsmithArmor": "زره‌ساز زره داد به",
    "tool.flow.action.heirIntroOnly": "فقط شب معارفه",
    "tool.flow.action.armorsmith.selfOnce": "زره‌ساز می‌تواند فقط ۱ بار در کل بازی به خودش زره بدهد.",
    "tool.flow.ocean.result.good": "شهروند بود → ۲۰ ثانیه فرصت گفت‌وگو.",
    "tool.flow.ocean.result.bad": "مافیا/زودیاک بود → اوشن از بازی خارج می‌شود.",
    "tool.flow.action.apply": "ثبت اکشن‌ها",
    "tool.flow.bomb.active": "بمب فعال است (خواب نیم‌روز)",
    "tool.flow.bomb.inactive": "بمب فعال نیست",
    "tool.flow.kane.revealTitle": "آشکارسازی همشهری کین",
    "tool.flow.kane.revealBody": "شب گذشته همشهری کین این بازیکن را برای شهر آشکار کرد — این بازیکن عضو تیم مافیاست.",

    "tool.lastMove.title": "کارت حرکت آخر",
    "tool.lastMove.none": "این سناریو کارت حرکت آخر ندارد!",
    "tool.lastMove.header": "کارت‌های حرکت آخر:",
    "tool.lastMove.draw": "قرعه کارت",
    "tool.lastMove.result": "نتیجه:",
    "tool.lastMove.allUsed": "همهٔ کارت‌ها استفاده شده‌اند.",

    "tool.roleChange.title": "تغییر نقش",
    "tool.roleChange.needDeal": "ابتدا نقش‌ها را تقسیم کنید.",
    "tool.roleChange.pick": "یک نفر را انتخاب کن تا نقشِش را تغییر بدهی",
    "tool.roleChange.labelPlayer": "نقش ایشون رو",
    "tool.roleChange.labelRole": "تغییر بده به",
    "tool.roleChange.apply": "اعمال تغییر نقش",
    "tool.roleChange.shuffleAll": "بر زدن نقش‌ها (همه)",
    "tool.roleChange.shuffleConfirm": "تأیید بر زدن نقش‌ها",
    "tool.roleChange.shuffleWarn": "هشدار: این کار نقش‌های همهٔ بازیکن‌ها را جابه‌جا می‌کند و قابل برگشت نیست.",

    "tool.chance.title": "قرعه",
    "tool.chance.ask": "چند نفر وارد قرعه می‌شوند؟",
    "tool.chance.count": "تعداد",
    "tool.chance.spin": "قرعه",
    "tool.chance.result": "نتیجه:",

    "tool.timer.pick.title": "تنظیم تایمر",
    "tool.timer.pick.ask": "مدت زمان «{label}» را انتخاب کنید",
    "tool.timer.pick.seconds": "زمان (ثانیه)",
    "tool.timer.pick.apply": "ثبت",
    "tool.timer.pick.back": "بازگشت",
    "tool.timer.title": "تایمر",
    "tool.timer.turn": "ترن",
    "tool.timer.challenge": "چالش",
    "tool.timer.defense": "دفاعیه",
    "tool.timer.reset": "ریست",
    "tool.timer.close": "بستن",

    "lifeSheet.title": "وضعیت بازیکن",
    "lifeSheet.role": "نقش",
    "lifeSheet.team": "تیم",
    "lifeSheet.status": "وضعیت",
    "lifeSheet.alive": "زنده",
    "lifeSheet.dead": "مرده",
    "lifeSheet.deadShot": "کشته شد (شات)",
    "lifeSheet.deadVote": "خارج شد (رای)",
    "lifeSheet.deadShortShot": "مرده",
    "lifeSheet.deadShortVote": "مرده",
    "lifeSheet.actionShot": "کشته شد",
    "lifeSheet.actionVote": "کشته شد",
    "lifeSheet.actionRevive": "برگرداندن به بازی (زنده)",

    "cast.noneMafia": "بدون مافیا",
    "cast.noneCity": "بدون شهر",
    "cast.stat.withInd": "بازیکن: {p} • مافیا: {m} • شهر: {c} • مستقل: {i}",
    "cast.stat.noInd": "بازیکن: {p} • مافیا: {m} • شهر: {c}",
  },
  en: {
    "doc.title": "Mafia Game Assistant",
    "app.title": "Mafia Game Assistant",
    "top.help": "Help",
    "top.lang.aria": "Change language",
    "top.lang.toFa": "فارسی",
    "top.lang.toEn": "English",

    "setup.title": "Game setup",
    "setup.backToSetup": "Back to setup",
    "setup.scenario": "Scenario",
    "setup.playersCount": "Players",
    "setup.mafiaCount": "Mafia",
    "setup.defaults": "Scenario defaults",
    "setup.start": "Start game",
    "setup.savedGame": "A saved game is available.",
    "setup.resume": "Resume",
    "setup.delete": "Delete",

    "players.title": "Players",
    "players.namesModeAria": "Names mode",
    "players.namesDefault": "Default names",
    "players.namesLast": "Last game names",
    "players.note": "Enter player names. If you choose “Last game names”, the app will use your browser’s saved list.",
    "players.deal": "Deal roles",
    "players.back": "Back to setup",

    "cards.title": "Deal",
    "cards.hint": "Each player picks a card and sees their role.",
    "cards.back": "Back",
    "cards.autoAssign": "Auto-assign roles",
    "cards.next": "Next step",

    "cast.title": "Cast list",
    "cast.back": "Back to setup",
    "cast.new": "New draw",

    "tools.wake": "Wake",
    "tools.status": "Status",
    "tools.lastMove": "Last move",
    "tools.roleChange": "Change role",
    "tools.chance": "Draw",
    "tools.timer": "Timer",
    "tools.flow": "Flow",

    "common.close": "Close",
    "common.seen": "Seen",
    "common.roleHelp": "Role help",
    "common.on": "On",
    "common.off": "Off",
    "common.done": "Done",
    "common.turn": "Turn",
    "common.playerN": "Player {n}",
    "common.cardN": "Card {n}",
    "common.taken": "Taken",

    "saveState.label": "Save: {state}",
    "error.config": "Invalid game setup.",
    "error.quick": "Setup error",
    "error.duplicateName": "Name “{name}” is duplicated.",

    "teams.mafia": "Mafia",
    "teams.city": "City",
    "teams.independent": "Independent",
    "teams.mafiaTeam": "Mafia team",
    "teams.cityTeam": "City team",

    "toggles.variableCount": "Count: variable",

    "quickStat.withInd": "Mafia: {m} • City: {c} • Ind: {i}",
    "quickStat.noInd": "Mafia: {m} • City: {c}",

    "help.title": "Help",
    "help.quick": "Quick guide",
    "help.body": `1) Choose scenario, number of players, and mafia count.<br />
2) Enable/disable roles (based on scenario).<br />
3) Tap “Start game” and enter player names.<br />
4) Tap “Deal roles”: each player picks a card and taps “Seen”.<br />
5) In “Cast list”, the narrator can use tools (Timer/Draw/Role change/Status).`,

    "tool.wake.title": "Wake order",
    "tool.wake.scenario": "Scenario: {name}",
    "tool.wake.none": "No wake order recorded for this scenario.",

    "tool.status.title": "Status check",
    "tool.status.alive": "Alive",
    "tool.status.dead": "Dead",
    "tool.status.mafiaAlive": "Mafia alive",
    "tool.status.mafiaDead": "Mafia dead",
    "tool.status.cityAlive": "City alive",
    "tool.status.cityDead": "City dead",
    "tool.status.indAlive": "Ind alive",
    "tool.status.indDead": "Ind dead",
    "tool.status.hint": "To change a player’s status, go to “Cast list”, tap the player, then choose “Killed”.",
    "tool.status.summary": "From your game {out} people are out. {m} Mafia, {c} Citizen and {i} independent.",

    "tool.flow.title": "Game Flow Runner",
    "tool.flow.needDeal": "Deal roles first.",
    "tool.flow.phase.day": "Day {n}",
    "tool.flow.phase.midday": "Mid-day sleep (Day {n})",
    "tool.flow.phase.night": "Night {n}",
    "tool.flow.step": "Step {i} of {n}",
    "tool.flow.next": "Next",
    "tool.flow.prev": "Back",
    "tool.flow.reset": "Reset flow",
    "tool.flow.timeline": "Timeline",
    "tool.flow.log": "Events",
    "tool.flow.addNote": "Add note",
    "tool.flow.notePlayer": "Player",
    "tool.flow.notePlaceholder": "What happened?",
    "tool.flow.saveNote": "Save",
    "tool.flow.day.talk": "Talk turns",
    "tool.flow.day.guns": "Gun use",
    "tool.flow.day.gunExpiry": "Gun expiry",
    "tool.flow.day.gunExpiry.desc": "The players below have an unused real gun and will be eliminated when you click Next.",
    "tool.flow.day.gunExpiry.none": "All real guns have been used — no one is eliminated by this step.",
    "tool.flow.guns.title": "Guns manager",
    "tool.flow.guns.hasGun": "Players with guns",
    "tool.flow.guns.add": "Give a gun",
    "tool.flow.guns.giveTo": "Give to",
    "tool.flow.guns.type": "Gun type",
    "tool.flow.guns.type.real": "Real",
    "tool.flow.guns.type.fake": "Fake",
    "tool.flow.guns.selfFakeOnly": "Gunslinger can give a gun to anyone, but can only give themselves a fake gun.",
    "tool.flow.guns.nightQuota": "Tonight quota: {n}/2 guns • real: {r}/1",
    "tool.flow.guns.limit2": "At most 2 guns per night.",
    "tool.flow.guns.limit1Real": "At most 1 real gun per night.",
    "tool.flow.guns.gunslingerIs": "Gunslinger: {name}",
    "tool.flow.guns.give": "Add gun",
    "tool.flow.guns.remove": "Remove gun",
    "tool.flow.guns.shooter": "Shooter",
    "tool.flow.guns.target": "Target",
    "tool.flow.guns.fire": "Record shot",
    "tool.flow.guns.noEffect": "Fake gun (no effect).",
    "tool.flow.guns.killedTarget": "Real gun (target is out).",
    "tool.flow.ocean.team": "Ocean team (tonight)",
    "tool.flow.ocean.add": "Add to Ocean team",
    "tool.flow.ocean.pick": "Pick player",
    "tool.flow.ocean.remove": "Remove from team",
    "tool.flow.day.vote": "Voting",
    "tool.flow.vote.hint": "Enter how many votes each alive player received.",
    "tool.flow.vote.votes": "Votes",
    "tool.flow.vote.apply": "Save votes",
    "tool.flow.vote.clear": "Clear",
    "tool.flow.vote.total": "Total votes: {n}",
    "tool.flow.vote.leaders": "Top votes",
    "tool.flow.defense.hint": "Based on recorded votes, players who reached majority should defend.",
    "tool.flow.defense.threshold": "Majority threshold: {n} (more than half of {v} voters)",
    "tool.flow.defense.none": "No one reached the threshold.",
    "tool.flow.defense.needVotes": "Record the Voting step first.",
    "tool.flow.defense.list": "Defense list",
    "tool.flow.elim.hint": "After defense, enter elimination votes for suspects. Highest votes = out. If tied, use Draw.",
    "tool.flow.elim.votes": "Elim votes",
    "tool.flow.elim.apply": "Save result",
    "tool.flow.elim.clear": "Clear",
    "tool.flow.elim.noCandidates": "No one is in the defense list.",
    "tool.flow.elim.result": "Result",
    "tool.flow.elim.out": "Out",
    "tool.flow.elim.draw": "Draw among ties",
    "tool.flow.elim.tie": "Tie",
    "tool.flow.elim.notChosenYet": "Not chosen yet",
    "tool.flow.elim.single.need": "Vote-out threshold: {n} votes (more than half of {v} voters)",
    "tool.flow.elim.single.notEnough": "Not enough votes: {c} of {n}",
    "tool.flow.day.outcome": "Day outcome",
    "tool.flow.outcome.none": "No one was voted out today.",
    "tool.flow.outcome.votedOut": "Voted out:",
    "tool.flow.outcome.lastMove": "Last move card (vote-out only)",
    "tool.flow.endCards.title": "End card",
    "tool.flow.endCards.for": "End card for {name}: {card}",
    "tool.flow.day.defense": "Defense",
    "tool.flow.day.eliminate": "Elimination",
    "tool.flow.day.toNight": "Go to night",
    "tool.flow.midday.sleepVote": "Eyes-closed vote",
    "tool.flow.midday.resolve": "Resolve mid-day",
    "tool.flow.night.wake": "Wake order",
    "tool.flow.night.actions": "Record night actions",
    "tool.flow.night.run": "Night order & actions",
    "tool.flow.night.resolve": "Wrap up night → Day",
    "tool.flow.action.mafiaShot": "Mafia shot",
    "tool.flow.action.doctorSave": "Doctor saved",
    "tool.flow.action.detectiveQuery": "Detective checks",
    "tool.flow.action.professionalShot": "Professional shot",
    "tool.flow.action.bomber": "Bomber placed bomb on",
    "tool.flow.action.bombCode": "Code",
    "tool.flow.action.magicianDisable": "Magician disabled",
    "tool.flow.action.zodiacShot": "Zodiac shot",
    "tool.flow.action.oceanWake": "Ocean woke",
    "tool.flow.action.kaneMark": "Citizen Kane marked",
    "tool.flow.action.constantineRevive": "Constantine revived",
    "tool.flow.action.nostPick3": "Nostradamus picked 3",
    "tool.flow.action.heirPick": "Heir picked",
    "tool.flow.action.herbalistPoison": "Herbalist poisoned",
    "tool.flow.action.herbalistAntidote": "Herbalist antidote",
    "tool.flow.action.armorsmithArmor": "Armorsmith armored",
    "tool.flow.action.heirIntroOnly": "Intro night only",
    "tool.flow.action.armorsmith.selfOnce": "Armorsmith can armor themselves only once per game.",
    "tool.flow.ocean.result.good": "Citizen → 20 seconds chat.",
    "tool.flow.ocean.result.bad": "Mafia/Zodiac → Ocean is out.",
    "tool.flow.action.apply": "Record actions",
    "tool.flow.bomb.active": "Bomb is active (mid-day sleep)",
    "tool.flow.bomb.inactive": "No active bomb",
    "tool.flow.kane.revealTitle": "Citizen Kane's Reveal",
    "tool.flow.kane.revealBody": "Last night, Citizen Kane revealed this player to the city — they are a Mafia member.",

    "tool.lastMove.title": "Last move card",
    "tool.lastMove.none": "This scenario has no Last Move card.",
    "tool.lastMove.header": "Last move cards:",
    "tool.lastMove.draw": "Draw card",
    "tool.lastMove.result": "Result:",
    "tool.lastMove.allUsed": "All cards have been used.",

    "tool.roleChange.title": "Change role",
    "tool.roleChange.needDeal": "Deal roles first.",
    "tool.roleChange.pick": "Choose a player to change their role",
    "tool.roleChange.labelPlayer": "Change role of",
    "tool.roleChange.labelRole": "Change to",
    "tool.roleChange.apply": "Apply",
    "tool.roleChange.shuffleAll": "Shuffle all roles",
    "tool.roleChange.shuffleConfirm": "Confirm shuffle",
    "tool.roleChange.shuffleWarn": "Warning: this shuffles everyone’s roles and cannot be undone.",

    "tool.chance.title": "Draw",
    "tool.chance.ask": "How many players are in the draw?",
    "tool.chance.count": "Count",
    "tool.chance.spin": "Draw",
    "tool.chance.result": "Result:",

    "tool.timer.pick.title": "Set timer",
    "tool.timer.pick.ask": "Select duration for “{label}”",
    "tool.timer.pick.seconds": "Time (seconds)",
    "tool.timer.pick.apply": "Save",
    "tool.timer.pick.back": "Back",
    "tool.timer.title": "Timer",
    "tool.timer.turn": "Turn",
    "tool.timer.challenge": "Challenge",
    "tool.timer.defense": "Defense",
    "tool.timer.reset": "Reset",
    "tool.timer.close": "Close",

    "lifeSheet.title": "Player status",
    "lifeSheet.role": "Role",
    "lifeSheet.team": "Team",
    "lifeSheet.status": "Status",
    "lifeSheet.alive": "Alive",
    "lifeSheet.dead": "Dead",
    "lifeSheet.deadShot": "Killed (shot)",
    "lifeSheet.deadVote": "Out (vote)",
    "lifeSheet.deadShortShot": "Dead",
    "lifeSheet.deadShortVote": "Dead",
    "lifeSheet.actionShot": "Killed",
    "lifeSheet.actionVote": "Killed",
    "lifeSheet.actionRevive": "Revive (alive)",

    "cast.noneMafia": "No mafia",
    "cast.noneCity": "No city",
    "cast.stat.withInd": "Players: {p} • Mafia: {m} • City: {c} • Ind: {i}",
    "cast.stat.noInd": "Players: {p} • Mafia: {m} • City: {c}",
  },
};
